[features]
seeds = false
skip-lint = false
[programs.devnet]
nft = "Hh4BCNVtf7kFnPk4xtoeutUQYTVzpjvfMi8EkdBo8ArS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
